version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: go-app-image
    container_name: go-app
    ports:
      - "8080:8080"
    # Important to bind/mount your codebase dir to /app dir for live reload
    volumes:
      - ./:/app