name: Terraform Apply

on:
  push:
    paths: terraform/**
    branches: main


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2

      - name: Change to Terraform directory
        run: cd ./terraform

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
