name: Terraform Apply

on:
  push:
    paths: [terraform/**, .github/workflows/terraform-apply.yml]
    branches: main

# allow use id-token
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::666607936402:role/terraform-project-github-actions

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init & Apply
        working-directory: ./terraform
        run: terraform init && terraform apply -auto-approve
